# Site settings
title: data science projects
subtitle: Data Science Blog
email: aeint.ngon@gmail.com
description: "Showcasing some personal projects of Aeint Thet Ngon"
baseurl: ""
markdown: kramdown
