# Site settings
title: data science projects
subtitle: Data Science Blog
email: aeint.ngon@gmail.com
description: "Showcasing some personal projects"
baseurl: ""
url: "https://aeintngon.github.io"
twitter_username: aeintthetngon
github_username:  aeintngon
