theme: jekyll-theme-dinky

title : Aeint Ngon
author :
  name : Aeint T Ngon
  email : aeint.ngon@gmail.com
  github : aeintngon
  twitter_username : aeintthetngon
  feedburner : nil

markdown: kramdown
JB :
  version : 0.3.0
